# Generated by Django 3.0.4 on 2020-04-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_events', to='users.AppUser')),
            ],
        ),
    ]
