# Generated by Django 3.0.4 on 2020-04-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_balanceevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceevent',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('1stplace', '1st place'), ('2ndplace', '2nd place'), ('3rdplace', '3rd place'), ('referral', 'Referral'), ('creator', 'Creator')], max_length=8),
        ),
    ]
