# Generated by Django 3.0.4 on 2020-04-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_is_copy'),
        ('users', '0004_auto_20200407_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceevent',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='quiz.Quiz'),
        ),
    ]
