# Generated by Django 3.0.4 on 2020-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appusertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='avatar',
            field=models.TextField(default='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAAAAABVicqIAAACs0lEQVR4Ae3YWU/bQBSG4W88TrOBSRMaqQVStfT//yFoqhYKCaROQrwvM5WQQCgsPnPG+CrvRXIz0uNjeyzZQuP92yE75LEdskN2yA4Bik0UZ4WCdNu9ft95B0Qt/eDpWnkw2hP1Iup2XmC73mdP1IisL1O8lHfSrgtRlwu8kjMZ1oPk0xCvNz4SNSDZWYq3Gn6tVBxUVJy/bcD/o20RPU1Q0b+5LXIdoLKrwA4JZyD0W9kg+gKU0rkNsopAap7zET0DLbXgI1EMYgvNRnxQyzdcRK9Bbs1FsoyOsCcJQS8pmUgCE4WJZCZIzkRKE6RgItoE0UxEmCCCiUgTRDKRlgnSYiJtE6TNRHomg3An6Uo6sg8mIjw64nERDMmGc8BGvA9UZCjZiBhTkTHYCA6JW2XUsUCcY5Ihv8ACwWBAQY5bVoiYEK79cAgrBO6prDL6E2GJoFul9E6dGt60wmn+1vPkm4saEGS/QrzWpyMHtSBQ89nLy1ongxrf45OrFZ4lx2MJIkIrXiwLPK0zGrn1f1tR4V2YlBqA43b3vI54r69EuiyVcKRDBOiIVmned1+erfXBqQPJ/XWkIA+H26enDFerAu7+R8+xRNKZ/7Cg4/V7LSHuRyuSKAjVw308PpQEhLw/HFcK6KJUW9vleCDoyPOdTmwwcXlI9DMHufb3LgeJzkoYJH/0zR/16bmRgfI8MkbUtAAMlcwU+RvDtGKqzJDgFuZFV0aIvgCnm8AE8WOwutB0RM/AK/bpyCoFs2tNRm7BLVtSkSQAuxtNRJbgF8U0RNsg8GlIltggK01CNrApixtAcEdBdGiHbChIkdkhoSYgEexSCQFJYFnUBEKZJG0CyWyRtBrRuS2S6Uqk1LaIUpVIAevyJpCyElFNIGUTiLZHVBOnS2MrF/aJ+5/H/+cH/h8Plh6yEC/PsQAAAABJRU5ErkJggg=='),
        ),
    ]
