# Generated by Django 3.0.4 on 2020-04-25 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yk_id', models.CharField(db_index=True, max_length=36)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('finished', models.BooleanField(default=False)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='users.AppUser')),
            ],
        ),
    ]
