# Generated by Django 3.0.4 on 2020-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_deposit_is_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appusertoken',
            name='push_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
