# Generated by Django 3.0.4 on 2020-07-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_appusertoken_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='processed',
            field=models.BooleanField(default=False, help_text='Info for admin only'),
        ),
    ]
