# Generated by Django 3.0.4 on 2020-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizparticipation_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
        migrations.AddField(
            model_name='quizparticipation',
            name='answer_points',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizparticipation',
            name='time_points',
            field=models.BigIntegerField(default=0),
        ),
    ]
