# Generated by Django 3.0.4 on 2020-04-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200401_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizparticipation',
            name='winner',
        ),
        migrations.AddField(
            model_name='quizparticipation',
            name='place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
