# Generated by Django 3.0.4 on 2020-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200402_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizparticipation',
            name='win',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True),
        ),
    ]
