# Generated by Django 3.0.4 on 2020-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizparticipation_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='author_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=32),
        ),
    ]
