# Generated by Django 3.0.4 on 2020-04-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200406_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_copy',
            field=models.BooleanField(default=False),
        ),
    ]
