# Generated by Django 3.0.4 on 2020-04-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_is_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
