# Generated by Django 3.0.4 on 2020-04-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quizcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizparticipation',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
