# Generated by Django 3.0.4 on 2020-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_quizparticipation_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
