# Generated by Django 3.0.4 on 2020-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20200430_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
